version: '3.3'
services:
    setup:
        image: michaelpc/perl-base:latest
        user: root
        volumes:
            - cpanfiles:/app/cpanfiles
        command: chmod 0700 -R /app && chown 1000 -R /app
    carton:
        image: michaelpc/openshift:latest
        volumes:
            - cpanfiles:/app/cpanfiles
            - ./:/app/src
        env_file:
            - ./cpanfile.env
        command: echo
    rnd:
        image: michaelpc/perl-base:latest
        volumes:
            - cpanfiles:/app/cpanfiles
            - ./:/app/src
        env_file:
            - ./cpanfile.env
        working_dir: /app/src
        environment:
            - IF_IN_RUN_0000000100=00
    build:
        image: michaelpc/perl-base:latest
        volumes:
            - cpanfiles:/app/cpanfiles
            - ./:/app/src
        env_file:
            - ./cpanfile.env
        working_dir: /app/src
        environment:
            - IF_IN_RUN_0000000100=00
        command: |
            rm -v README.md;
            carton exec dzil clean;
            carton exec dzil build;
            cp -v Object-GMP-*/README.mkdn README.md
    release:
        image: michaelpc/perl-base:latest
        volumes:
            - cpanfiles:/app/cpanfiles
            - ./:/app/src
        env_file:
            - ./cpanfile.env
        working_dir: /app/src
        environment:
            - IF_IN_RUN_0000000100=00
volumes:
    cpanfiles:
